services:
  - type: web
    name: task-management-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "backend.app:app"
    repo: https://github.com/thuinanutshell/task-management-app
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_ENV
        value: production
